import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#edf8ff",
        "on-background": "#243036",
        surface: "#edf8ff",
        "surface-bright": "#edf8ff",
        "surface-dim": "#c3d7e3",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#e4f3fc",
        "surface-container": "#dbebf4",
        "surface-container-high": "#d4e5ef",
        "surface-container-highest": "#cde0ea",
        "surface-variant": "#cde0ea",
        "surface-tint": "#8b4b00",
        "on-surface": "#243036",
        "on-surface-variant": "#515d64",
        "inverse-surface": "#041015",
        "inverse-on-surface": "#929fa6",
        primary: "#8b4b00",
        "primary-dim": "#7a4100",
        "primary-container": "#ff8f00",
        "primary-fixed": "#ff8f00",
        "primary-fixed-dim": "#eb8300",
        "inverse-primary": "#ff8f00",
        "on-primary": "#fff0e6",
        "on-primary-container": "#462300",
        "on-primary-fixed": "#1e0c00",
        "on-primary-fixed-variant": "#532b00",
        secondary: "#0e666a",
        "secondary-dim": "#00595d",
        "secondary-container": "#a6eff3",
        "secondary-fixed": "#a6eff3",
        "secondary-fixed-dim": "#98e1e5",
        "on-secondary": "#c8fcff",
        "on-secondary-container": "#005b5f",
        "on-secondary-fixed": "#00474a",
        "on-secondary-fixed-variant": "#0e666a",
        tertiary: "#6d5a00",
        "tertiary-dim": "#5f4e00",
        "tertiary-container": "#fdd400",
        "tertiary-fixed": "#fdd400",
        "tertiary-fixed-dim": "#edc600",
        "on-tertiary": "#fff2ce",
        "on-tertiary-container": "#594a00",
        "on-tertiary-fixed": "#433700",
        "on-tertiary-fixed-variant": "#645300",
        error: "#b02500",
        "error-dim": "#b92902",
        "error-container": "#f95630",
        "on-error": "#ffefec",
        "on-error-container": "#520c00",
        outline: "#6c7980",
        "outline-variant": "#a2afb6",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        display: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Be Vietnam Pro", "sans-serif"],
        label: ["Be Vietnam Pro", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
