#!/usr/bin/env bash
# Seeds a LOCAL Supabase (`supabase start`) with test users and a sample course outline,
# and writes .env.local pointing the app at it. Never run against a hosted project.
#
# Test accounts (local only, password for all: LocalTest!2026):
#   owner@bonded.test   — bootstrap owner (ADMIN_EMAILS)
#   editor@bonded.test  — gets "editor" by claiming a pending invite on first login
#   student@bonded.test — enrolled student
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

STATUS="$(supabase status -o env 2>/dev/null)"
API_URL="$(sed -n 's/^API_URL="\(.*\)"$/\1/p' <<<"$STATUS")"
ANON_KEY="$(sed -n 's/^ANON_KEY="\(.*\)"$/\1/p' <<<"$STATUS")"
SERVICE_KEY="$(sed -n 's/^SERVICE_ROLE_KEY="\(.*\)"$/\1/p' <<<"$STATUS")"
DB_URL="$(sed -n 's/^DB_URL="\(.*\)"$/\1/p' <<<"$STATUS")"

case "$API_URL" in
  http://127.0.0.1:*|http://localhost:*) ;;
  *) echo "Refusing to seed: API_URL '$API_URL' is not a local Supabase" >&2; exit 1 ;;
esac

PASSWORD="LocalTest!2026"

create_user() {
  curl -sS -o /dev/null -w "%{http_code} $1\n" -X POST "$API_URL/auth/v1/admin/users" \
    -H "apikey: $SERVICE_KEY" -H "Authorization: Bearer $SERVICE_KEY" -H "Content-Type: application/json" \
    -d "{\"email\":\"$1\",\"password\":\"$PASSWORD\",\"email_confirm\":true,\"user_metadata\":{\"full_name\":\"$2\"}}"
}

create_user owner@bonded.test "Owner"
create_user editor@bonded.test "Editor"
create_user student@bonded.test "Student"

psql "$DB_URL" -v ON_ERROR_STOP=1 -q <<'SQL'
insert into public.staff_invites (email, role) values ('editor@bonded.test', 'editor')
  on conflict do nothing;

-- Sample outline for the seeded "kinetic-basics" course (idempotent).
do $$
declare m1 uuid; m2 uuid; s1 uuid;
begin
  if exists (select 1 from public.modules where course_id = 'kinetic-basics') then return; end if;
  insert into public.modules (course_id, title, position, published) values ('kinetic-basics', 'The Bond', 1, true) returning id into m1;
  insert into public.modules (course_id, title, position, published) values ('kinetic-basics', 'Feeding Drive', 2, false) returning id into m2;
  insert into public.modules (course_id, parent_id, title, position, published) values ('kinetic-basics', m1, 'Building Trust', 1, true) returning id into s1;
  insert into public.lessons (course_id, module_id, position, title, published) values
    ('kinetic-basics', m1, 1, 'Welcome', true),
    ('kinetic-basics', m1, 2, 'A Dog Is...', true),
    ('kinetic-basics', s1, 1, 'A Secret Language', true),
    ('kinetic-basics', s1, 2, 'The Skills Map', false),
    ('kinetic-basics', m2, 1, 'Every Dog Needs To Eat', true);
end $$;

insert into public.enrollments (user_id, course_id, source)
  select id, 'kinetic-basics', 'grant' from auth.users where email = 'student@bonded.test'
  on conflict do nothing;
SQL

cat > .env.local <<ENV
# Generated by scripts/seed-local.sh — points at the LOCAL Supabase only.
NEXT_PUBLIC_SUPABASE_URL=$API_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_KEY
ADMIN_EMAILS=owner@bonded.test
NEXT_PUBLIC_SITE_URL=http://localhost:3100
ENV
echo "Seeded local Supabase and wrote .env.local"
