import { blocks } from "./shared";

/**
 * The Privacy Policy. Every statement here describes what the product does today (see
 * docs/legal-review-2026-10-04.md for the source of each one); change the product and this together.
 */
export const PRIVACY_HTML = blocks(
  "<p>This policy explains what personal information Bonded collects, why, who receives it and what choices you have. By “we” and “us” we mean the business below.</p>",
  "<h2>Who we are</h2>",
  "{{business_details}}",
  "<p>You can reach us about anything in this policy at <a href=\"mailto:{{contact_email}}\">{{contact_email}}</a>.</p>",

  "<h2>What we collect</h2>",
  "<h3>Information you give us</h3>",
  "<ul>",
  "<li><strong>Account:</strong> your name, email address and a password (stored only in scrambled form), or your Google account name and email if you sign in with Google. Optional profile details such as your location, goals, photo and time zone.</li>",
  "<li><strong>Your dogs:</strong> names, photos and details you add about them, and the skills you mark as learned.</li>",
  "<li><strong>Learning and practice:</strong> the courses you can access, lesson progress, quiz answers, practice sessions and plans, routines, music you upload, and certificates.</li>",
  "<li><strong>Videos you send to Roni:</strong> training videos you upload to get personal feedback, with her notes and replies. They may show you, your voice, other people and the inside of your home. Please don&#39;t film anyone who hasn&#39;t agreed.</li>",
  "<li><strong>Community and stories:</strong> posts, comments and photos you share, and stories you submit through our public form. Anything you make public can be seen by others.</li>",
  "<li><strong>Quiz and sign-ups:</strong> your first name, email and answers when you take our “Find your journey” quiz, and whether you agreed to marketing emails.</li>",
  "<li><strong>Support:</strong> questions you ask Roni or the team, and help requests.</li>",
  "<li><strong>AI assistant:</strong> the messages you type to our AI assistant, and the lesson or page you were on when you asked.</li>",
  "</ul>",
  "<h3>Information from payments</h3>",
  "<p>Card payments are processed by <strong>PayPlus</strong>, an Israeli payment gateway. You enter your card details on PayPlus&#39;s secure payment page. We never see or store your full card number. PayPlus tells us whether the payment succeeded, the amount and currency, the payment method type and a reference, which we keep with your order so we can give you access, issue a receipt and handle refunds.</p>",
  "<h3>Information collected automatically</h3>",
  "<ul>",
  "<li>Technical data your browser sends (IP address, device and browser type, pages visited), used for security, to keep you signed in and, with your consent where the law asks for it, for analytics.</li>",
  "<li>Your time zone, so reminders arrive at the right hour.</li>",
  "<li>Whether our emails were delivered, opened or bounced.</li>",
  "</ul>",

  "<h2>Why we use it, and our legal basis</h2>",
  "<ul>",
  "<li><strong>To run your account and deliver what you bought</strong> (courses, practice tools, feedback from Roni, community). Basis: performing our contract with you.</li>",
  "<li><strong>To take payment, issue receipts and keep the records the law requires.</strong> Basis: contract and legal obligation.</li>",
  "<li><strong>To email you about your account, purchases, replies from Roni and changes to the service.</strong> These messages are part of the service and are not marketing.</li>",
  "<li><strong>To send news and training tips by email.</strong> Basis: your consent (see “Marketing emails” below).</li>",
  "<li><strong>To send reminders and phone notifications</strong> you asked for. Basis: your consent; you can turn them off in Settings or in your browser.</li>",
  "<li><strong>To keep the service secure and prevent abuse</strong> (for example bot protection on forms). Basis: our legitimate interest.</li>",
  "<li><strong>To understand how the site and app are used and improve them.</strong> Basis: your consent where the law requires it, otherwise our legitimate interest. See “Cookies and analytics”.</li>",
  "<li><strong>To answer your questions and defend legal claims.</strong> Basis: contract and legitimate interest.</li>",
  "</ul>",
  "<p>If you are in the EU, the UK or Switzerland, these are the legal bases we rely on under the GDPR. We don&#39;t make decisions about you by automated means that have legal or similarly significant effects.</p>",

  "<h2>Marketing emails</h2>",
  "<p>When you create an account you see a box asking whether we may email you Roni&#39;s training tips and updates. In the United States the box starts ticked and you can untick it. Everywhere else, including Israel, the EU and the UK, it starts unticked and we email you tips only if you tick it. You can change your mind at any time in Settings, or with the unsubscribe link in any marketing email. We keep a record of when you agreed, where, and from which country, as proof of your choice, and delete that record when you withdraw. Emails about your account and purchases continue, because they are part of the service.</p>",

  "<h2>Who receives your information</h2>",
  "<p>We don&#39;t sell your personal information and we don&#39;t share it for advertising. We use these service providers, each only for the purpose described:</p>",
  "<ul>",
  "<li><strong>Supabase</strong> — database, sign-in and file storage.</li>",
  "<li><strong>Vercel</strong> — hosting of the website and app.</li>",
  "<li><strong>Vimeo</strong> — streaming of lesson videos.</li>",
  "<li><strong>Mux</strong> — processing and playback of videos members upload.</li>",
  "<li><strong>Resend</strong> — sending our emails.</li>",
  "<li><strong>PayPlus</strong> — payments and refunds.</li>",
  "<li><strong>PostHog</strong> — analytics (see “Cookies and analytics”).</li>",
  "<li><strong>Cloudflare Turnstile</strong> — checks that forms are filled in by people.</li>",
  "<li><strong>Google</strong> — only if you choose “Sign in with Google”.</li>",
  "<li><strong>Anthropic</strong> — our AI provider: your messages to the AI assistant are sent to it to produce a reply. We use it under commercial terms that don&#39;t allow your messages to be used to train its models.</li>",
  "<li><strong>Browser push services</strong> (Apple, Google, Mozilla) — to deliver phone and desktop notifications you turned on.</li>",
  "</ul>",
  "<p>Roni and our team can see your account, progress and the videos and messages you send them. We may also disclose information when the law requires it, or to protect our rights, and to a buyer if the business is sold, who would be bound by this policy.</p>",

  "<h2>Transfers abroad</h2>",
  "<p>We operate from Israel, and our providers run servers in other countries, including the United States and the European Union. Israel is recognised by the European Commission as providing an adequate level of data protection. For providers outside the EU/UK we rely on the EU–US and UK–US Data Privacy Framework where the provider is certified, and otherwise on standard contractual clauses or equivalent safeguards. Transfers from Israel are made in line with the Israeli Privacy Protection Regulations on transfers abroad. Ask us if you want a copy of the safeguards.</p>",

  "<h2>How long we keep it</h2>",
  "<ul>",
  "<li><strong>Your account, dogs, progress, posts and uploaded files and videos:</strong> until you delete them or your account.</li>",
  "<li><strong>Payment records:</strong> the receipts and tax invoices we issue, and our payment ledger (amount, date, currency and payment reference), are kept for seven years after the transaction, because Israeli tax and bookkeeping law requires it. When you delete your account, your orders and subscription details are deleted and the ledger is kept without a link to your account.</li>",
  "<li><strong>Marketing consent record:</strong> until you withdraw it.</li>",
  "<li><strong>Support messages:</strong> for as long as needed to help you and to answer later questions.</li>",
  "<li><strong>Analytics:</strong> for a limited period set in our analytics tool.</li>",
  "<li><strong>Backups:</strong> deleted data leaves our backups as they are replaced on their regular cycle.</li>",
  "</ul>",

  "<h2 id=\"cookies\">Cookies and analytics</h2>",
  "<p>Necessary cookies keep you signed in, keep checkout secure and remember your cookie choice. They are always on.</p>",
  "<p>Analytics cookies are set by PostHog so we can see how people use the site and the app, for example which lessons are finished and where people get stuck. When you are signed in, this activity is linked to your account email. Where the law asks for it (such as in the EU, UK, Switzerland and Brazil) we ask before setting them; elsewhere they are on unless you turn them off. If you say no, we still count visits, anonymously and without cookies. You can change your choice at any time from “Cookie settings” at the bottom of every page. We keep a record of each choice (when, what and which region&#39;s rule applied) as proof.</p>",
  "<p>If you are a paying member, we also analyse your activity in the courses you bought (such as lessons completed, practice sessions and videos sent to Roni) on our own servers, to run and improve the service. This uses no cookies and continues even if you turn analytics cookies off.</p>",
  "<p>If your browser sends a Global Privacy Control signal, we treat it as a request to turn analytics cookies off, as California and other US state laws require.</p>",

  "<h2>Your rights</h2>",
  "<p>Depending on where you live (Israel, the EU, the UK, California and other places), you can ask us to:</p>",
  "<ul>",
  "<li>show you the information we hold about you, and give you a copy;</li>",
  "<li>correct information that is wrong;</li>",
  "<li>delete your information;</li>",
  "<li>stop using it for marketing, or object to other uses based on our legitimate interest;</li>",
  "<li>move it to another service;</li>",
  "<li>withdraw a consent you gave, at any time, without affecting what happened before.</li>",
  "</ul>",
  "<p>Most of this you can do yourself in the member area: <strong>Settings → Download my data</strong> gives you a file with your information, and <strong>Settings → Delete account</strong> removes your profile, dogs, progress, uploaded files and videos (we keep only what the law requires, such as payment records). For anything else, email <a href=\"mailto:{{contact_email}}\">{{contact_email}}</a>. We answer within 30 days. We may need to check it is really you first.</p>",
  "<p>If you are not happy with our answer you can complain to the privacy regulator where you live, for example the Israeli Privacy Protection Authority, your national data protection authority in the EU, or the Information Commissioner&#39;s Office in the UK. We would appreciate the chance to fix it first.</p>",
  "<p>If we told you that giving us certain information is optional, you can say no without losing the service, except where we need the information to provide it (for example your email to create an account).</p>",
  "<p><strong>California and other US states.</strong> We do not sell personal information or share it for cross-context advertising, and we honour Global Privacy Control. Within the last twelve months we collected the categories described above (identifiers, account and purchase records, internet activity, and content you uploaded, which can include audio and video) for the purposes described above, and disclosed them to the providers listed above. You will not be treated differently for using your privacy rights.</p>",

  "<h2>Videos and AI</h2>",
  "<p>Videos you send to Roni are used to give you feedback. We don&#39;t use facial recognition or voiceprints to identify anyone. You are talking to an AI, not a person, when you use the AI assistant; it can be wrong and is not veterinary advice, and you shouldn&#39;t enter sensitive information in it.</p>",

  "<h2>Children</h2>",
  "<p>Bonded is for adults. You must be 18 or older (or the age of majority where you live) to create an account or buy. We don&#39;t knowingly collect information from children. If you think a child has an account, tell us and we will delete it.</p>",

  "<h2>Security</h2>",
  "<p>We protect your information with encryption in transit, access controls and the security measures of the providers above, and we limit who on our team can see it. No system is perfectly secure. If a breach affects you, we will tell you and the regulator as the law requires.</p>",

  "<h2>Changes to this policy</h2>",
  "<p>If we change this policy in a way that matters, we will update the date at the top and, for big changes, tell you by email or in the app.</p>",
);
